apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: kyugo/flask-redis
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: app-config